add_executable(cpp1 "basicfunctions.cpp")
install(TARGETS cpp1 RUNTIME DESTINATION bin)

add_executable(cpp2 "types.cpp")
install(TARGETS cpp2 RUNTIME DESTINATION bin)

add_executable(cpp3 "whileloops.cpp")
install(TARGETS cpp3 RUNTIME DESTINATION bin)

add_executable(cpp4 "forloops.cpp")
install(TARGETS cpp4 RUNTIME DESTINATION bin)

add_executable(cpp5 "cpp5.cpp")
install(TARGETS cpp5 RUNTIME DESTINATION bin)

add_executable(cpp6 "classes.cpp")
install(TARGETS cpp6 RUNTIME DESTINATION bin)

add_executable(cpp7 "privpubclasses.cpp")
install(TARGETS cpp7 RUNTIME DESTINATION bin)

add_executable(cpp8 "memberfun.cpp")
install(TARGETS cpp8 RUNTIME DESTINATION bin)

add_executable(cpp9 "inheritance1.cpp")
install(TARGETS cpp9 RUNTIME DESTINATION bin)

add_executable(cpp10 "inheritance2.cpp")
install(TARGETS cpp10 RUNTIME DESTINATION bin)

add_executable(cpp11 "inheritance3.cpp")
install(TARGETS cpp11 RUNTIME DESTINATION bin)

add_executable(cpp12 "randnum.cpp")
install(TARGETS cpp12 RUNTIME DESTINATION bin)

add_executable(cpp13 "inputoutput.cpp")
install(TARGETS cpp13 RUNTIME DESTINATION bin)

add_executable(cpp14 "smartpointers.cpp")
install(TARGETS cpp14 RUNTIME DESTINATION bin)


add_executable(cpp15 "smartpointers2.cpp")
install(TARGETS cpp15 RUNTIME DESTINATION bin)
